# Generated by Django 4.2 on 2024-08-29 13:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=20000)),
                ('job_type', models.CharField(choices=[('Intership', 'Intership'), ('PartTime', 'PartTime'), ('PartTime', 'PartTime'), ('Contract', 'Contract')], max_length=45)),
                ('education', models.CharField(choices=[('PHD', 'PHD'), ('Master', 'Master'), ('Bachelor', 'Bachelor')], max_length=45)),
                ('experience', models.CharField(choices=[('NoExperience', 'NoExperience'), ('Junior', 'Junior'), ('Mid-Level', 'Mid-Level'), ('Senior', 'Senior')], max_length=45)),
                ('salary', models.IntegerField(blank=True, null=True)),
                ('position', models.CharField(max_length=100)),
                ('due_date', models.DateField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('user', models.IntegerField()),
                ('company', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='JobApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('resume', models.FileField(upload_to='resumes')),
                ('cover_letter', models.TextField(max_length=2000)),
                ('applied_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_job', to='job.job')),
            ],
        ),
    ]
