version: '3.8'

services:
  users:
    build: ./users
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8001"
    ports:
      - "8001:8001"
    container_name: UsersApi
    volumes:
      - ./users:/app
    environment:
      - USER_DB_NAME=users
      - USER_DB_USER=postgres
      - USER_DB_PASSWORD=postgres
      - USER_DB_HOST=userDB
    depends_on:
      - userDB

  jobs:
    build: ./jobs
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8002"
    ports:
      - "8002:8002"
    container_name: JobApi
    volumes:
      - ./jobs:/app
    environment:
      - JOB_DB_NAME=jobs
      - JOB_DB_USER=postgres
      - JOB_DB_PASSWORD=postgres
      - JOB_DB_HOST=jobsDB
    depends_on:
      - jobsDB

  blog:
    build: ./blog
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8003"
    ports:
      - "8003:8003"
    container_name: BlogApi
    volumes:
      - ./blog:/app
    environment:
      - BLOG_DB_NAME=blog
      - BLOG_DB_USER=postgres
      - BLOG_DB_PASSWORD=postgres
      - BLOG_DB_HOST=blogDB
    depends_on:
      - blogDB

  userDB:
    image: postgres:16
    environment:
      - POSTGRES_DB=users
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - user-data:/var/lib/postgresql/data

  jobsDB:
    image: postgres:16
    environment:
      - POSTGRES_DB=jobs
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - job-data:/var/lib/postgresql/data

  blogDB:
    image: postgres:16
    environment:
      - POSTGRES_DB=blog
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - blog-data:/var/lib/postgresql/data

volumes:
  user-data:
  job-data:
  blog-data:
